template_sentences = ['A room for {month} for {adults} adults',
'Can I book a room for {adults} adults and {children} children?',
'Can I book a room for a group of {adults} persons this {special_date}?',
'Can I find a room for {adults} persons in {month}?',
'Can I get a room for {adults} adults and {children} children this {month}?',
'Can I get a room for {adults} adults this {special_date}?',
'Can I have a reservation for {adults} adults and {children} teenagers in {month}?',
'Can I inquire about room availability for a group of {adults} during {special_date}?',
'Can I reserve a room for the {special_date}?',
'Can you book a room for {adults} adults this {special_date}?',
'Can you help me find a room for {adults} adults and {children} children in {month}?',
'Can you help me find a room for {adults} persons during {special_date}?',
'Can you help me find a room for {adults} adults this {special_date}?',
'Can you reserve a room for {adults} adults and {children} children in {month}?',
'Can you reserve a room for {adults} adults in {month}?',
'Could I get a reservation for {adults} adults and {children} children in {month}?',
'Could I reserve a room for {adults} adults and {children} children for {days} days in {month}?',
'Could you assist me in booking a room for {days} days for {adults} adults this {special_date}?',
'Could you assist me in finding a room for {adults} adults during {special_date}?',
'Could you check room availability for {adults} adults for {days} days this {special_date}?',
'Could you check the availability for {adults} persons for {days} days during {special_date}?',
'Could you reserve a room for {adults} adults during {special_date}?',
'Could you reserve a room for {adults} during {special_date}?',
'Do you have any availability for {adults} adults this {special_date}?',
'Do you have any rooms available for {special_date}?',
'Do you have room availability for {adults} adults during {special_date}?',
'Do you have rooms available for {days} days for {adults} adults this {special_date}?',
'I am interested in a room for {adults} adults and {children} teenagers in {month}.',
'I am interested in booking a room for {adults} adults and {children} children in {month}.',
'I am looking for a room for {adults} adults and {children} children for {days} days in {month}.',
'I need a reservation for {adults} adults and {children} children in {month}.',
'I need a room for {adults} adults and {children} kids for {days} days in {month}.',
'I need a room for {days} days for {adults} adults in {month}.',
'I need to book a room for {adults} adults during {special_date}.',
'I need to book a room for {special_date}.',
'I want to reserve a room for {adults} adults for {days} days in {month}.',
'I would like to book a room for {adults} adults and {children} children this {special_date}.',
'I would like to reserve a room for {adults} adults and {children} children for {days} days in {month}.',
'I would like to reserve a room for {adults} persons during {month}.',
"I'd like to book a room for {adults} adults and {children} children.",
"I'm interested in booking a room for {adults} adults for {days} days this {special_date}.",
"I'm looking for a room for {adults} adults for {days} days during {special_date}.",
"I'm looking for a room over the {special_date} for {adults} adults.",
"I'm looking to book a room for {adults} adults in {month}.",
'Is a room available for {adults} adults for {days} days?',
'Is there a room available for {adults} adults and {children} teenagers during {special_date}?',
'Is there a room available for a group of {adults} persons for {days} days in {month}?',
'Is there a room available for {adults} guests for {days} days in {month}?',
'Is there any availability for a room for {adults} adults and {children} children in {month}?',
'Is there any availability for {adults} adults and {children} children this {special_date}?',
'Is there any availability for {adults} adults for {days} days in {month}?',
'Is there any availability for {adults} guests for {days} days in {month}?',
'Is there any room available during {special_date}?',
'Is there any room available for {adults} adults in {month}?',
'Is there availability for {adults} adults and {children} children during {special_date}?',
'I’d like to book a room for {adults} adults and {children} children in {month}.',
'I’d like to book a room for {adults} guests in {month}.',
'I’d like to book a room for {adults} guests in {month}.',
'I’d like to inquire about a room for {adults} guests for {days} days in {month}.',
'I’d like to inquire about a room for {adults} guests for {days} days in {month}.',
'Looking for a room for {adults} adults for {days} days during {special_date}.',
'Looking for a room for {adults} guests for {days} days during {special_date}.',
'Looking for a room suitable for {adults} for {days} days in {month}.',
'Looking for availability for {adults} adults and {children} children in {month}.',
'Looking for room availability for {adults} adults and {children} children in {month}.',
'room for {adults} guests in {month}',
"Is there room availability for {adults} adults this {month}?",
"Can I get a room in {month} for {adults} adults?",
"Can you book a room for {adults} adults in {month}?",
"I am seeking a room for {adults} adults and {children} children this {month}.",
"I need room availability for {adults} adults and {children} children in {month}.",
"Could you book a room for {adults} adults and {children} children in {month}?",
"I’d like to book a room for {adults} adults this {special_date}.",
"Can you find a room for {adults} adults and {children} children in {month}?",
"I want to book a room for {adults} adults in {month}.",
"I am looking for room availability for {adults} adults in {month}.",
"Could I have a room for {adults} guests and {children} children in {month}?",
"Is a room available for {adults} adults in {month}?",
"Can you assist in finding a room for {adults} adults this {month}?",
"I am inquiring about a room for {adults} adults in {month}.",
"I need to reserve a room for {adults} adults this {month}.",
"Can I have a room for {adults} adults this {special_date}?",
"Could you help book a room for {adults} adults in {month}?",
"I would like to find a room for {adults} adults this {month}.",
"I need to find a room for {adults} adults in {month}.",
"Can you check availability for {adults} adults in {month}?",
"Can I have a room for {adults} adults in {month}?",
"I am interested in a room for {adults} adults this {month}.",
"Could I book a room for {adults} guests in {month}?",
"Is there availability for {adults} adults in {month}?",
"Can I reserve a room for {adults} adults this {month}?",
"I would like to reserve a room for {adults} adults in {month}.",
"Do you have a room for {adults} adults available in {month}?",
"I want to find room availability for {adults} adults in {month}.",
"Could you find a room for {adults} adults in {month}?",
"I need a room reservation for {adults} adults in {month}.",
"Is there a room for {adults} adults available this {month}?",
"Can you help me reserve a room for {adults} in {month}?",
"I’d like to reserve a room for {adults} adults this {month}.",
"Can I have room availability for {adults} adults in {month}?",
"I need to book a room for {adults} adults this {month}.",
"Could you check a room for {adults} adults in {month}?",
"I am looking to book a room for {adults} adults in {month}.",
"I want to reserve a room for {adults} adults and {children} children this {month}.",
"Is there any room for {adults} adults available in {month}?",
"Can I get a room for {adults} adults and {children} children in {month}?",
"I would like a room for {adults} adults in {month}.",
"Can you help me book a room for {adults} adults and {children} children in {month}?",
"Do you have any room available for {adults} adults this {month}?",
"Is there any availability for {adults} adults this {month}?" ,
"I'd like to book a room for {adults} adults for {days} days in {month}.",
"Can I get a room for {adults} adults for {days} days?",
"I need a room for {days} days in {month}.",
"Looking for a room for {days} days for {adults}.",
"Is there availability for {adults} adults for {days} days in {month}?",
"I am looking to book a room for {adults} adults for {days} days.,"
"I want to reserve a room for {days} days in {month} for {adults} adults.",
"Can you find a room for {adults} adults for {days} days?",
"Looking for room availability for {adults} adults for {days} days in {month}.",
"I need to book a room for {adults} adults for {days} days.",
"I want to make a booking that includes {children} children.", 
"I need a booking for {days} days including {children} children.", 
"I'm looking to book a room for {special_date} with space for {children} children.", 
"Can I get a booking for {special_date} with {children} teenagers?", 
"I'd like to reserve a room for {special_date} for {children} children.", 
"Looking to book a room for {children} children for {days} days.", 
"I am interested in booking a room with {children} children for {special_date}.", 
"I need a reservation for {special_date} with {children} children.", 
"Can you book a room for {children} children for {days} nights?", 
"I wish to make a reservation for {special_date} with {children} children.", 
"Looking for a room for {children} children for {days} nights.", 
"I want to make a reservation for {children} kids.", 
"Can I book a room for {children} children on {special_date}?", 
"I need a room for {children} children for {days} days.", 
"I'd like to book a room for {children} children.", 
"Can you find a room for {children} children for {days} nights?", 
"I am seeking a room for {children} children on {special_date}.", 
"I need room availability for {children} children on {special_date}.", 
"Could you book a room for {children} children for {days} days?", 
"I’d like to book a room for {children} children on {special_date}.", 
"Can you find a room for {children} children on {special_date}?", 
"I want to book a room for {children} children for {days} days.", 
"I am looking for room availability for {children} kids on {special_date}.", 
"Seeking to book a room for {children} children for {days} nights.", 
"I need to make a reservation for {children} kids.", 
"Looking to book a room for {children} children on {special_date}.", 
"I want a booking for {special_date} with {children} children.", 
"Checking availability for a room for {children} kids for {days} days.", 
"I'd like to reserve a room for {children} children for {days} nights.",
"I need a booking for {special_date}.",
"I want to book a room for {children} kids.",
"Looking for a room on {special_date} for {children} kids.",
"Can you find availability for {children} youngsters?",
"I'm interested in booking a room for {special_date}.",
"I need a reservation for {children} kids.",
"Can you book a room for {special_date}?",
"Looking for room availability for {children} youngsters.",
"I need to make a reservation for {special_date}.",
"Can I get a room for {children} kids?",
"I am looking for a booking for {special_date}.",
"I want to make a reservation for {children} youngsters.",
"Can you find a room for {special_date} for {children} youngsters?",
"I'd like to book a room for {children} kids.",
"Looking for availability on {special_date}.",
"I am interested in booking a room for {children} youngsters.",
"I want a booking for {special_date} with {children} youngsters.",
"I am seeking a room for {children} kids on {special_date}.",
"I'd like to reserve a room for {children} youngsters.",
"Checking availability for a room for {children} kids.",
"I need a room for {children} youngsters on {special_date}.",
"Can you book a room for {children} youngsters?",
"I want to make a reservation for {children} kids.",
"Looking for room availability on {special_date} for {children} youngsters.",
"I'd like to book a room for {children} kids on {special_date}.",
"Can you find a room for {children} youngsters?",
"I want a booking for {children} kids on {special_date}.",
"Looking to book a room for {children} youngsters.",
"I am looking for room availability for {children} kids.",
"I wish to make a reservation for {children} youngsters on {special_date}.",
"Looking for a room for {children} kids.",
"I need to book a room for {children} youngsters.",
"Can I reserve a room for {children} kids on {special_date}?",
"I am interested in a room for {children} youngsters.",
"I want to reserve a room for {children} kids.",
"Checking room availability for {children} youngsters on {special_date}.",
"I need to make a booking for {children} kids.", 
"I need a booking for {special_date}.", 
"I'm looking to book a room for {special_date}.", 
"Can you find availability for {special_date}?", 
"I'm interested in booking a room for {special_date}.", 
"Can you book a room for {special_date}?", 
"I need to make a reservation for {special_date}.", 
"I am looking for a booking for {special_date}.", 
"Can you find a room for {special_date}?", 
"I'd like to book a room for {special_date}.", 
"Looking for availability on {special_date}.", 
"I want a booking for {special_date}.", 
"Checking availability for a room for {special_date}.", 
"I want to reserve a room for {special_date}.", 
"I am interested in booking a room for {special_date}.", 
"I want to make a reservation for {special_date}.", 
"Looking to book a room for {special_date}.", 
"I am looking for room availability for {special_date}.", 
"I wish to make a reservation for {special_date}.", 
"I am seeking a room for {special_date}.", 
"Can I get a room for {special_date}?", 
"Looking for room availability on {special_date}.", 
"I need to book a room for {special_date}.", 
"Can I reserve a room for {special_date}?", 
"Checking room availability for {special_date}.", 
"I need to make a booking for {special_date}.", 
"I am inquiring about room availability for {special_date}.", 
"Can you provide room options for {special_date}?", 
"I am planning to book a room for {special_date}.", 
"Is there room availability for {special_date}?", 
"Looking for a room booking on {special_date}.", 
"I am searching for room availability on {special_date}.", 
"I want to book a stay for {special_date}.", 
"I am interested in a room booking for {special_date}.", 
"Looking to reserve a room for {special_date}.", 
"I wish to book a room for {special_date}.", 
"Checking for room availability on {special_date}.", 
"I am hoping to book a room for {special_date}.", 
"I'd like to reserve a room on {special_date}.", 
"I am checking room availability for {special_date}.", 
"I am interested in room availability on {special_date}.", 
"I want to book a room for {children} children.", 
"Can you find availability for {children} children?", 
"I need a reservation for {children} children.", 
"Looking for room availability for {children} children.", 
"Can I get a room for {children} children?", 
"I want to make a reservation for {children} children.", 
"Can you find a room for {children} children?", 
"I'd like to book a room for {children} children.", 
"I am looking for room availability for {children} children.", 
"I wish to make a reservation for {children} children.", 
"I am interested in booking a room for {children} children.", 
"I want to reserve a room for {children} children.", 
"Checking availability for a room for {children} children.", 
"I need to book a room for {children} children.", 
"Can I reserve a room for {children} children?", 
"I am seeking a room for {children} children.", 
"I am interested in a room for {children} children.", 
"I am hoping to book a room for {children} children.", 
"I'd like to reserve a room for {children} children."]
